[tool.poetry]
name = "vietnam-provinces"
version = "0.1.0"
description = "Library to provide list of Vietnam administrative divisions (tỉnh thành, quận huyện, phường xã)."
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
single-version = "^1.1"
click = "^7.0"
requests = "^2.23.0"
logbook = "^1.5.3"
pydantic = "^1.4"
unidecode = "^1.1.1"
python-rapidjson = "^0.9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
devtools = "^0.5.1"
pytest-flake8 = "^1.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
